### ISSUE TITLE
Why does the test suite depend on Cabal < 1.25?

### ISSUE THREAD

**Issue by peti** [haskell/hackage-security#188]
The library supports current development versions of Cabal, but the test suite does not. Is that intentional?

**Comment by hvr** [comment]
I assume you're referring to the released version on Hackage? That's because the testsuite fails to build with Cabal-2.0:

```
tests/TestSuite.hs:256:24: error:
    Data constructor not in scope: PackageName :: [Char] -> PackageName
    |
256 |            pkgname @?= PackageName "foo"
    |                        ^^^^^^^^^^^

tests/TestSuite.hs:266:41: error:
    Data constructor not in scope: PackageName :: [Char] -> PackageName
    |
266 |     testEntryIndexFile = IndexPkgPrefs (PackageName "foo")
    |                                         ^^^^^^^^^^^

```

However, this is already fixed in Git, so the next Hackage release will resolve this.

**Comment by peti** [comment]
OK, I see. Thank you very much for the quick response.
